# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            网络咖啡
description:      Simple is best!
url:              http://hijoe.net
domain:           hijoe.net
# email:            joe@gmail.com
twitter_username: bestop
# github_username:  bestop
github_repo:      https://github.com/bestop/pala.github.io
google_analytics: UA-55
timezone:         America/New_York
subscribe:        http://feed.hijoe.net
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - newpost.rb
  - CNAME
header_pages:
  - apps.md
  - tag.md
  - category.md
  - archive.md
  - search.html
