# Dependencies
markdown:         kramdown

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            NetCafe
description:      Copyright © HiJoe.NET All Rights Reserved.
url:              http://hijoe.net
domain:           hijoe.net
# email:            joe@gmail.com
# twitter_username: bestop
# github_username:  bestop
github_repo:      https://github.com/bestop/netcafe
google_analytics: UA-55
timezone:         America/New_York
subscribe:        http://feed.hijoe.net
baseurl: ""
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - newpost.rb
  - CNAME
header_pages:
  - tag.md
  - archive.md
  - about.md
  - notes.html
  - links.md
  

#comments_provider: gitalk
## https://github.com/gitalk/gitalk#install
#gitalk:    
#  owner: bestop    
#  repo: blog-comments    
#  clientID: 902761aa4b0965b2b1f5    
#  clientSecret: 56d2316c736e221f2aca6f6c17cb1050d3b83afd
